apiVersion: v1
kind: Service
metadata:
  name: cups-service
  namespace: cups-dropwizard-ns
spec:

  selector:
    app: cups-service
  type: NodePort  # Exposes the service on a NodePort
  ports:
    - name: http  # ✅ Ensure a name is provided
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Optional: Specify a static NodePort (30000-32767)
